# Docker Compose file for TheZoo 
version: "3.3"
services:
#############################
#  Minio Storage container #
############################
  minio:
    image: minio/minio
    command: server /data
    volumes:
      - /tmp/minio:/data
    ports:
      - "0.0.0.0:9000:9000"
    env_file:
      - mwdb-vars.env
#############################
#  Redis container         #
############################
  redis:
    image: redis:alpine

#############################
#  Postgres DB container    #
############################
  postgres:
    image: postgres
    restart: always
    env_file:
      # NOTE: use gen_vars.sh in order to generate this file
      - mwdb-vars.env
#############################
#   MWDB-core container    #
############################
  mwdb:
    build:
      context: ./mwdb-core
      dockerfile: deploy/docker/Dockerfile
    depends_on:
      - postgres
      - redis
      - minio
    restart: on-failure
    env_file:
      # NOTE: use gen_vars.sh in order to generate this file
      - mwdb-vars.env
    volumes:
      - "./TheZoo/mwdb/mail_templates:/app/mail_templates"
      - "./TheZoo/mwdb/app:/app/mwdb"
#############################
#   MWDB-web container     #
############################
  mwdb-web:
    depends_on:
      - mwdb
    build:
      context: ./mwdb-core
      dockerfile: deploy/docker/Dockerfile-web-dev
    ports:
      - "9090:9090"
    volumes:
      - "./TheZoo/mwdb/public:/app/public"
      - "./TheZoo/mwdb/src:/app/src"
    restart: on-failure

